### PR TITLE
Parse event description as HTML. Initial implementation of #68

### PR DESCRIPTION
**Pull request by dmfs**

### CODE REVIEW

**Review by lemonboston — APPROVED** [review]
Looks okay to me.
Maybe we could change the link color from red to something else?
Also maybe in the next round the ImageGetter could be added to the Html call, I searched for GlideImageGetter and there are code samples for it (unfortunately it's not just a one liner call it seems).

**Comment by dmfs** [comment]
I think links use the accent color by default. I need to check how to change that. But we certainly should.

We're not going to support images in the description. The server should strip `` tags.

**Comment by dmfs** [comment]
I've updated the code to use the primary color for links instead.  @lemonboston please check it out.

**Comment by lemonboston** [comment]
Checked, it is better with this color imo, too.

The deprecated getColor() method call can be replaced with `ContextCompat`:
`ContextCompat.getColor(getContext(), R.color.schedjoules_colorPrimary)`

**Pull request merged**
