### PR TITLE
Fix link key mismatches between client and API. Fix bug about incorre…

### PR DESCRIPTION
**Pull request by lemonboston**
…ct booking type check. Move all link constants to one place. #261 

---

In addition to double-checking all Link string literals against the API documentation and also checking the rest in logs, I've also moved all of them as constants to one class. I think it gives a better overview, easier to double-check them later as well, less chance for mistake by defining them scattered in the codebase. Static inner classes are used so they aren't even initialized until used. That can be further refined if needed.
The property type constants are defined as `PropertyType` already for convenience.

I've also fixed the bug in this pull request as well about the incorrect check for the booking type.
(It is also fixed in another PR that may not make master eventually (about ticket statuses)).

### CODE REVIEW

**Comment by dmfs** [comment]
I just thought that this would make more sense to be in the `java-api-client`. Is there anything Android specific in these rel types?

**Comment by lemonboston** [comment]
I thought about that, I think that the only reason for keeping it in the SDK is that if any of it changes, for example we add new ones, we don't need another `java-api-client` release. It's a bit similar to what you said about the benefit of the JSON format in general, so it can be changed without changing 'intermediaries', validators, etc.
Also, not all properties are defined now I think.. for example sale-start, sale-end, ticket-price.

**Review by dmfs — APPROVED** [review]
I general I think this should go to the java-api-client. But it's certainly better to wait for the rel-types to stabilize a bit more. Let's get back to this in a couple of months.

**Comment by lemonboston** [comment]
I vote for 3 story points for this.

**Pull request merged**
