### PR TITLE
Bugs/186 fix location picker theme

### PR DESCRIPTION
**Pull request by dmfs**
This updates the theme of the location picker. Note the branch is based on PR #185

### CODE REVIEW

**Review by lemonboston — CHANGES_REQUESTED** [review]
It looks nice where these UI changes go. Location picker items look nicer to me, too, with the new text sizes.

Just curious, do you plan any divider, elevation to the bottom of the header items? Or does that still depend on what we come up for the event list date header?
The "Recent locations" feels a  bit detached or strange now for me.

`MessageItem` with its layout has been udpated for the new Current Location look, but it is used for unrecovarable errors as well. So I suppose we need another layout for that. I think it can be the same as the buttoned version, just without the button.

`schedjoules_list_item_place_suggestion.xml` - the extra content text has no color set now, so I suppose it uses the primary text color of the theme. It looks good imo, but the text color usage may start to be a bit inconsistent then. I updated a note about this primary, secondary text attribute in the fine tuning story, so we can address it there. https://github.com/schedjoules/android-event-discovery-sdk/issues/183

**Comment by lemonboston** [comment]
It seems a bit too spacious vertically for me, I think smaller area could be enough to get comfortable tapping. That way we could maybe show more items (?).
(Not important of course, we can change later as well.)

`MessageItem` with its layout `schedjoules_list_item_location_message.xml` is still used for unrecoverable errors and for CURRENT LOCATION as well. Or was that deliberate?
If you check `MessageItem` constructor usage, you can see the other 3 use points.
So I think current location needs its own item and layout.

`<dimen name="schedjoules_list_subheader_height">48dp</dimen>` is not used.

**Comment by dmfs** [comment]
The spacing follows material design for two-line list items. With the previous item height, it would be harder to distinguish items without having dividers. We could go for the dense version of the list item, but that would require a smaller font.

I'll check the subheader height dimension. Apparently i forgot to apply it :-o
I didn't check MessageItem, but I can look into that.

**Review by lemonboston — APPROVED** [review]

**Comment by lemonboston** [comment]
All looks good to me now.

**Pull request merged**
