### PR TITLE
PR for 20 unit test for listitems merge

### PR DESCRIPTION
**Pull request by lemonboston**
@dmfs please review

These are only 2 unit test cases for checking the merge of items.
I will continue with https://github.com/schedjoules/android-event-discovery-sdk/issues/21 to cover and check the actual behaviors of the list much more.
(That will help to verify the bugs in the sprint backlog.)

### CODE REVIEW

**Comment by lemonboston** [comment]
@dmfs updated with master, please review.
(the message of the last commit is incorrect, please ignore that)

**Comment by lemonboston** [comment]
@dmfs Please review this. I've just updated with master. It contains some changes to production code as well - a fix to an unnoticed bug if I remember correctly. I think as a minimum it's enough to review just the production code change.
After this is merged I will update the other testing PR as well and request the review on that.

**Comment by dmfs** [comment]
Please resolve the merge conflicts.

**Comment by lemonboston** [comment]
Merge conflicts resolved.

**Review by dmfs — APPROVED** [review]

**Pull request merged**
