### PR TITLE
PR for 138: Remove horizontal action bar

### PR DESCRIPTION
**Pull request by lemonboston**
Implements #138.

@dmfs Please review.

### CODE REVIEW

**Comment by lemonboston** [comment]
I've modeled both VenueName and AddressName as optional here, not sure thought it's correct. I've seen events without venue, but I don't know if there should always be an address.
For me it would help if there was an API documentation about the response fields.

**Comment by lemonboston** [comment]
Rebased to master, ready for review.

**Comment by dmfs** [comment]
Will this conflict with #147? If not, please rebase on master.

**Comment by dmfs** [comment]
Looks ok otherwise.

**Comment by lemonboston** [comment]
Rebased on master, ready for review again.

(I don't think it will conflict with 147 - I am not sure why you asked here, but in general it's not a problem for me to update branches and resolve the conflicts multiple times.)

**Review by dmfs — APPROVED** [review]

**Pull request merged**
